[under-tian]
title = "Portionen under tian"
subtitle = "Bra mat för dig, din plånbok och planeten"
author = "Hanna Olvenmark"
ISBN = "9789177753056"
release = 2022-12-29T00:00:00Z

[under-tian-300]
title = "Portionen under tian"
subtitle = "300-kronorsveckorna"
author = "Hanna Olvenmark"
ISBN = "9789177751052"
release = 2019-11-21T00:00:00Z

[nyfiken-gron]
title = "Nyfiken grön"
subtitle = "mero vego - mindre regler"
author = "Cecilia Blankens, Kristin Johansson"
ISBN = "9789113096308"
release = 2019-05-10T00:00:00Z
