agg = "ägg"
apelsinskal = "apelsinskal"
bacon = "bacon"
baileys = "baileys"
bakpulver = "bakpulver"
basilika = "basilika"
bladspenat = "bladspenat"
blomkalshuvud = "blomkålshuvud"
bovetemjol = "bovetemjöl"
chilipulver = "chilipulver"
chokladsas = "chokladsås"
citronsaft = "citronsaft"
cremefraiche = "crème fraiche"
curry = "curry"
dijonsenap = "dijonsenap"
dragon = "dragon"
falukorv = "falukorv"
farskost = "färskost"
fiskbuljong = "fiskbuljongtärning"
florsocker = "florsocker"
garam_masala = "garam masala"
glass = "glass"
gradde = "grädde"
gronsaksbuljong = "grönsakbuljongstärning"
inlagd_paprika = "inlagd paprika"
is = "is"
kahlua = "kahlúa"
kanel = "kanel"
kardemumma = "kardemumma"
ketchup = "ketchup"
kokosflingor = "kokosflingor"
kokosmjolk = "kokosmjölk"
kottbuljong = "köttbuljongstärning"
kottfars = "köttfärs"
krossadetomater = "krossade tomater"
kycklingbuljong = "kycklingbuljongstärning"
kycklingfile = "kycklingfilé"
kyckling = "kyckling"
lasagneplattor = "lasagneplattor"
laxfile = "laxfilé"
limejuice = "limejuice"
limevodka = "limevodka"
ljus_rom = "ljus rom"
lok = "gul lök"
majs = "majs"
majsstarkelse = "majsstärkelse"
mandelmassa = "mandelmassa"
mango_chutney = "mango chutney"
matvete = "matvete"
mjolk = "mjölk"
mjol = "mjöl"
morot = "morötter"
mynta = "mynta"
olja = "olja"
oregano = "oregano"
paprika = "paprika"
paprikapulver = "paprikapulver"
parmesan = "finriven pecorino eller parmesan"
passeradetomater = "passerade tomater"
pasta = "pasta"
persilja = "persilja"
ris = "ris"
riven_ost = "riven ost"
roda_linser = "röda linser"
rodvin = "rödvin"
rotselleri = "rotselleri"
saffran = "saffran"
salt_peppar = "salt och peppar"
salt = "salt"
sambal_oelek = "sambal oelek"
santa_maria_paneng_red_curry = "Santa Maria® Paneng Red Curry"
smor = "smör"
sockerlag = "sockerlag"
socker = "socker"
sodavatten = "sodavatten"
soja = "soja"
spaghetti = "spaghetti"
sprite = "sprite"
strimlad_skinka = "strimlad skinka"
svarta_linser = "svarta belugalinser"
sweet_chili = "sweet chilisås"
sylt = "sylt"
tabasco = "tabasco"
tacokrydda = "tacokrydda"
tandoori = "tandoori"
teriyakisas = "teriyakisås"
timjan = "timjan"
tomatpure = "tomatpuré"
vaniljsocker = "vaniljsocker"
vatten = "vatten"
vetemjol = "vetemjöl"
vit_choklad = "vit choklad"
vitloksklyfta = "vitlöksklyfta"
vodka = "vodka"
