agg = "ägg"
bacon = "bacon"
chilipulver = "chilipulver"
cremefraiche = "crème fraiche"
dragon = "dragon"
falukorv = "falukorv"
glass = "glass"
gradde = "grädde"
is = "is"
kottbuljong = "köttbuljongstärning"
kottfars = "köttfärs"
krossadetomater = "krossade tomater"
kycklingfile = "kycklingfilé"
limevodka = "limevodka"
lok = "gul lök"
majs = "majs"
mango_chutney = "mango chutney"
mjolk = "mjölk"
mjol = "mjöl"
paprikapulver = "paprikapulver"
parmesan = "finriven pecorino eller parmesan"
passeradetomater = "passerade tomater"
ris = "ris"
salt_peppar = "salt och peppar"
sambal_oelek = "sambal oelek"
spaghetti = "spaghetti"
sprite = "sprite"
sweet_chili = "sweet chilisås"
sylt = "sylt"
tabasco = "tabasco"
tacokrydda = "tacokrydda"
teriyakisas = "teriyakisås"
tomatpure = "tomatpuré"
vitloksklyfta = "vitlöksklyfta"
