agg = "ägg"
bacon = "bacon"
baileys = "baileys"
basilika = "basilika"
blomkalshuvud = "blomkålshuvud"
bovetemjol = "bovetemjöl"
chilipulver = "chilipulver"
chokladsas = "chokladsås"
cremefraiche = "crème fraiche"
curry = "curry"
dijonsenap = "dijonsenap"
dragon = "dragon"
falukorv = "falukorv"
florsocker = "florsocker"
garam_masala = "garam masala"
glass = "glass"
gradde = "grädde"
gronsaksbuljong = "grönsakbuljongstärning"
inlagd_paprika = "inlagd paprika"
is = "is"
kahlua = "kahlúa"
ketchup = "ketchup"
kokosmjolk = "kokosmjölk"
kottbuljong = "köttbuljongstärning"
kottfars = "köttfärs"
krossadetomater = "krossade tomater"
kycklingbuljong = "kycklingbuljongstärning"
kycklingfile = "kycklingfilé"
lasagneplattor = "lasagneplattor"
limejuice = "limejuice"
limevodka = "limevodka"
ljus_rom = "ljus rom"
lok = "gul lök"
majs = "majs"
majsstarkelse = "majsstärkelse"
mandelmassa = "mandelmassa"
mango_chutney = "mango chutney"
matvete = "matvete"
mjolk = "mjölk"
mjol = "mjöl"
morot = "morötter"
mynta = "mynta"
oregano = "oregano"
paprikapulver = "paprikapulver"
parmesan = "finriven pecorino eller parmesan"
passeradetomater = "passerade tomater"
pasta = "pasta"
ris = "ris"
riven_ost = "riven ost"
roda_linser = "röda linser"
rodvin = "rödvin"
rotselleri = "rotselleri"
saffran = "saffran"
salt_peppar = "salt och peppar"
salt = "salt"
sambal_oelek = "sambal oelek"
smor = "smör"
sockerlag = "sockerlag"
socker = "socker"
sodavatten = "sodavatten"
soja = "soja"
spaghetti = "spaghetti"
sprite = "sprite"
strimlad_skinka = "strimlad skinka"
svarta_linser = "svarta belugalinser"
sweet_chili = "sweet chilisås"
sylt = "sylt"
tabasco = "tabasco"
tacokrydda = "tacokrydda"
tandoori = "tandoori"
teriyakisas = "teriyakisås"
timjan = "timjan"
tomatpure = "tomatpuré"
vatten = "vatten"
vit_choklad = "vit choklad"
vitloksklyfta = "vitlöksklyfta"
vodka = "vodka"
