agg = "ägg"
bacon = "bacon"
blomkalshuvud = "blomkålshuvud"
chilipulver = "chilipulver"
cremefraiche = "crème fraiche"
curry = "curry"
dragon = "dragon"
falukorv = "falukorv"
garam_masala = "garam masala"
glass = "glass"
gradde = "grädde"
gronsaksbuljong = "grönsakbuljongstärning"
is = "is"
kokosmjolk = "kokosmjölk"
kottbuljong = "köttbuljongstärning"
kottfars = "köttfärs"
krossadetomater = "krossade tomater"
kycklingbuljong = "kycklingbuljongstärning"
kycklingfile = "kycklingfilé"
limevodka = "limevodka"
lok = "gul lök"
majs = "majs"
majsstarkelse = "majsstärkelse"
mango_chutney = "mango chutney"
mjolk = "mjölk"
mjol = "mjöl"
morot = "morötter"
paprikapulver = "paprikapulver"
parmesan = "finriven pecorino eller parmesan"
passeradetomater = "passerade tomater"
pasta = "pasta"
ris = "ris"
riven_ost = "riven ost"
roda_linser = "röda linser"
salt_peppar = "salt och peppar"
sambal_oelek = "sambal oelek"
smor = "smör"
spaghetti = "spaghetti"
sprite = "sprite"
strimlad_skinka = "strimlad skinka"
sweet_chili = "sweet chilisås"
sylt = "sylt"
tabasco = "tabasco"
tacokrydda = "tacokrydda"
teriyakisas = "teriyakisås"
tomatpure = "tomatpuré"
vatten = "vatten"
vitloksklyfta = "vitlöksklyfta"
