agg = "ägg"
bacon = "bacon"
chilipulver = "chilipulver"
falukorv = "falukorv"
glass = "glass"
gradde = "grädde"
lok = "gul lök"
mango_chutney = "mango chutney"
mjolk = "mjölk"
mjol = "mjöl"
paprikapulver = "paprikapulver"
parmesan = "finriven pecorino eller parmesan"
passeradetomater = "passerade tomater"
ris = "ris"
salt_peppar = "salt och peppar"
sambal_oelek = "sambal oelek"
spaghetti = "spaghetti"
sweet_chili = "sweet chilisås"
sylt = "sylt"
tabasco = "tabasco"
