[meta]
version = 1

[info]
title = "Chicken Teriyaki"
picture = "teriyaki"
portions = 4
bakingtime = 15
preptime = 10
bakingtemp = 175
source = {url = "https://www.ica.se/recept/chicken-teriyaki-med-gurka-726265"}

introduction = """
Fantasiskt enkel rätt på ett fåtal ingredienser! Bilden visar ett serveringsförslag med
havreris.
"""

[preparation]
ingredients = [
  {amount = 700, unit = "g", name = "kycklingfile"},
  {amount = 4, unit = "dl", name = "ris"},
  {amount = 300, unit = "ml", name = "teriyakisas"},
]

steps = [
  "Koka riser enligt anvisningen på förpackningen.",
  "Lägg kyckligen i en tillräckligt stor långpanna. Häll på teriyakisåsen. Ställ in i ugnen.",
]
