[meta]
version = "number"

[info]
title = "string"
-picture = "string"
-portions = "number"
-introduction = "string"
-bakingtime = "number"
-hint = "string"
-preptime = "number"
-bakingtemp = "number"

[info.-source]
-url = "string"
-book = "keyword"

[preparation]
steps = ["string"]

[[preparation.ingredients]]
# TODO: allow int or string if floats becomes a problem
-amount = "number"
-unit = "string"
name = "keyword"
-repeat = "number"

[[preparation.-optional-ingredients]]
-amount = "number"
-unit = "string"
name = "keyword"
-repeat = "number"
