name: Compile PDF

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: make texlive-full leiningen
          version: 2.0

      # latexmk doesn't work when restored from apt-cache
      - name: Install latexmk
        run: apt-get install -y latexmk

      - name: Compile PDF
        run: make

      - name: Upload artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: kokbok
          path: kokbok.pdf
          if-no-files-found: error
