name: Compile PDF

on:
  push:
    tags: [ v* ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # latexmk doesn't work when restored from a cache using awalsh128/cache-apt-pkgs-action unfortunately
      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y latexmk make texlive-full leiningen

      - name: Compile PDF
        run: make

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: kokbok
          path: kokbok.pdf
          if-no-files-found: error

      - name: Create release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: kokbok.pdf
          fail_on_unmatched_files: true
          generate_release_notes: true
