name: Compile PDF

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # latexmk doesn't work when restored from a cache using awalsh128/cache-apt-pkgs-action unfortunately
      - name: Install packages
        run: sudo apt-get install -y latexmk make texlive-full leiningen

      - name: Compile PDF
        run: make

      - name: Upload artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: kokbok
          path: kokbok.pdf
          if-no-files-found: error
